// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7L3tULDyM9YpCcg5vhhz7cl4AH0jzxro',
    appId: '1:236655272782:web:f76ba8e789461a34cb341f',
    messagingSenderId: '236655272782',
    projectId: 'fir-auth-7e924',
    authDomain: 'fir-auth-7e924.firebaseapp.com',
    storageBucket: 'fir-auth-7e924.appspot.com',
    measurementId: 'G-TJJ5YYNJ0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoy3wQEE1y8OF9Lr4Yi_PyvE-dxkMRJFc',
    appId: '1:236655272782:android:cbd8cda7825a8645cb341f',
    messagingSenderId: '236655272782',
    projectId: 'fir-auth-7e924',
    storageBucket: 'fir-auth-7e924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACv8ARWblSCYmICTQZyRutdr_STuF9n6E',
    appId: '1:236655272782:ios:bf230604344acb52cb341f',
    messagingSenderId: '236655272782',
    projectId: 'fir-auth-7e924',
    storageBucket: 'fir-auth-7e924.appspot.com',
    iosBundleId: 'com.example.flutterFirebasee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACv8ARWblSCYmICTQZyRutdr_STuF9n6E',
    appId: '1:236655272782:ios:70f489fea5a1cc90cb341f',
    messagingSenderId: '236655272782',
    projectId: 'fir-auth-7e924',
    storageBucket: 'fir-auth-7e924.appspot.com',
    iosBundleId: 'com.example.flutterFirebasee.RunnerTests',
  );
}
